name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Specifies the execution environment

    steps:
      - name: Checkout repository  # Step to check out the repository
        uses: actions/checkout@v2  # Uses the official action to check out the code

      - name: Set up Docker Buildx  # Optional step to set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: set lower case owner name
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image  # Step to build the Docker image
         run: |
          LOWERCASE_USER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$LOWERCASE_USER/docker-githubactions:latest .

      - name: Push Docker image to GitHub Container Registry  # Step to push the Docker image to the registry
          docker push ghcr.io/$LOWERCASE_USER/docker-githubactions:latest
