name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the workflow when a push is made to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Specifies the execution environment

    steps:
      - name: Checkout repository  # Step to check out the repository
        uses: actions/checkout@v3  # Uses the official action to check out the code

      - name: Set up Docker Buildx  # Optional step to set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image  # Step to build the Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Log in to GitHub Container Registry  # Step to log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GitHub Container Registry  # Step to push the Docker image to the registry
        run: docker push ${{ github.repository }}:${{ github.sha }}
