name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Déclenche sur tout push sur n'importe quelle branche

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Convert GitHub username to lowercase
    - name: Convert GitHub username to lowercase
      run: |
        username_lowercase=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        echo "::set-env name=GITHUB_USERNAME_LOWERCASE::${username_lowercase}"

    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.GITHUB_USERNAME_LOWERCASE }}
        password: ${{ secrets.CR_PAT }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.GITHUB_USERNAME_LOWERCASE }}/${{ github.event.repository.name | lower }}:latest .

    # Push the Docker image to the GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.GITHUB_USERNAME_LOWERCASE }}/${{ github.event.repository.name | lower }}:latest
