name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Déclenche sur tout push sur n'importe quelle branche

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest .

    # Convert repository name to lowercase
    - name: Convert repository name to lowercase
      id: convert_to_lowercase
      run: echo "::set-output name=repo_name::${{ github.event.repository.name | tolower }}"

    # Push the Docker image to the GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ steps.convert_to_lowercase.outputs.repo_name }}:latest
